# Generated by Django 3.2.23 on 2023-11-09 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elective',
            fields=[
                ('E_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('E_type', models.IntegerField(choices=[(1, 'E1'), (2, 'E2')])),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('F_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SRN', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('GPA', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveTeachingFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.IntegerField(default=0)),
                ('E_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.elective')),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.faculty')),
                ('room_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.room')),
            ],
        ),
    ]
