# Generated by Django 3.2.23 on 2023-11-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_student_srn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='elective',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='elective',
            name='last_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
