# Generated by Django 3.2.23 on 2023-11-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20231109_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='EF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.electiveteachingfaculty'),
        ),
    ]
