# Generated by Django 3.2.23 on 2023-11-10 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_student_ef'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='EF',
        ),
        migrations.AddField(
            model_name='student',
            name='EF1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='E1', to='website.electiveteachingfaculty'),
        ),
        migrations.AddField(
            model_name='student',
            name='EF2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='E2', to='website.electiveteachingfaculty'),
        ),
    ]
